// Public surface of core/board (explicit, to keep the package namespace small).
export {
  aspectValue,
  cameraBasis,
  framingBand,
  hFov,
  horizonLine,
  LENS_MM,
  NEAR_M,
  pickFocal,
  project,
  projectPoint,
  projectPolygon,
  REF_HEIGHT_M,
  sensorHeight,
  SENSOR_W_MM,
  solveBand,
  solveCamera,
  toCamera,
  unprojectAtDepth,
  unprojectToPlane,
  vFov,
  visibleHeight,
  type CameraBasis,
  type CameraSolution,
  type FocalSource,
  type Projected,
  type SolveCameraOptions,
} from './camera.ts';
export {
  DEPTH_FACTOR,
  FACING_REL,
  inferTemplate,
  isEnvProp,
  layoutBoard,
  PROP_SIZE,
  relativeYaw,
  SCREEN_X,
  worldXAtFrameX,
  yawForRel,
  yawLookAt,
  type LayoutContext,
  type RosterEntry,
} from './layout.ts';
export {
  buildPuppet,
  facingBucket,
  POSE_TABLES,
  poseTopY,
  VIEW_ANGLE,
  type PuppetShape,
  type PuppetView,
} from './puppets.ts';
export { buildFrameScene, frameSize, FRAME_W, type FrameScene } from './scene.ts';
export { renderBoard, renderPuppetPreview, RENDERER_VERSION, subjectFrameBoxes, subjectFramePoints, type RenderOptions } from './render.ts';
export { lintBoard, type BoardLintIssue, type LintOptions } from './lint.ts';
export {
  shotFields,
  standardBoard,
  STANDARD_LOOK,
  STANDARD_ROSTER,
  STANDARD_SHOTS,
  STANDARD_SIDES,
  subject as standardSubject,
  type StandardShot,
} from './fixtures/standard-shots.ts';
