import { defineConfig } from 'tsdown';

/**
 * Published package `storyscript-mov`: one ESM bundle for Node ≥24.15.
 * Workspace packages (contracts, core) are inlined; runtime dependencies stay
 * external (installed by npm); vite is dev-only and never bundled.
 * @resvg/resvg-wasm (MPL-2.0) stays an external dependency, unmodified.
 * No source maps are published.
 *
 * THIRD_PARTY_NOTICES.md (generated by `npm run licenses`) is copied into
 * dist/ so the notices for the bundled frontend ship with the package even
 * though package.json `files` only lists dist/ and web/ (npm packs README
 * and LICENSE on its own; scripts/copy-web.mjs puts those next to package.json).
 */
export default defineConfig({
  entry: { cli: 'src/cli.ts' },
  format: 'esm',
  platform: 'node',
  target: 'node24',
  outDir: 'dist',
  clean: true,
  dts: false,
  fixedExtension: true,
  sourcemap: false,
  copy: [{ from: '../../THIRD_PARTY_NOTICES.md', to: 'dist' }],
  deps: {
    alwaysBundle: [/^@storyscript\//],
    neverBundle: ['vite', /^node:/],
  },
});
