import { Setup } from '@storyscript/contracts';
import type { DbPort } from '../port.ts';

/**
 * setup ↔ contracts Setup (FR-06). `setup.shot_ids_json` (ordered) mirrors
 * `shot.setup_id`; every write here keeps the two in sync: a shot belongs to
 * at most one setup, so adding it to one removes it from any other.
 *
 * Which setups were generated by "derive" (and not edited since) is kept in
 * the kv table under AUTO_KEY — the setup table has no column for it.
 */

interface SetupRow {
  id: string;
  location_resource_id: string | null;
  label: string;
  shot_ids_json: string;
  resource_ids_json: string;
  durations_json: string;
  estimate_confirmed: number;
  revision: number;
}

const COLS = 'id, location_resource_id, label, shot_ids_json, resource_ids_json, durations_json, estimate_confirmed, revision';

function fromRow(r: SetupRow): Setup {
  return Setup.parse({
    id: r.id,
    location_resource_id: r.location_resource_id,
    label: r.label,
    shot_ids: JSON.parse(r.shot_ids_json),
    resource_ids: JSON.parse(r.resource_ids_json),
    durations: JSON.parse(r.durations_json),
    estimate_confirmed: r.estimate_confirmed === 1,
    revision: r.revision,
  });
}

/** Setups in insertion order (derive inserts them in narrative order of their first shot). */
export function listSetups(db: DbPort): Setup[] {
  return db.all<SetupRow>(`SELECT ${COLS} FROM setup ORDER BY rowid`).map(fromRow);
}

export function getSetup(db: DbPort, id: string): Setup | null {
  const r = db.get<SetupRow>(`SELECT ${COLS} FROM setup WHERE id = ?`, id);
  return r ? fromRow(r) : null;
}

function values(x: Setup) {
  return [
    x.location_resource_id,
    x.label,
    JSON.stringify(x.shot_ids),
    JSON.stringify(x.resource_ids),
    JSON.stringify(x.durations),
    x.estimate_confirmed ? 1 : 0,
  ] as const;
}

/**
 * Insert or overwrite a setup, then make shot.setup_id agree with it:
 * its shots point at it (and leave any other setup's list), shots it no
 * longer lists are detached.
 */
export function saveSetup(db: DbPort, s: Setup): void {
  const x = Setup.parse(s);
  const exists = db.get<{ id: string }>('SELECT id FROM setup WHERE id = ?', x.id);
  if (exists) {
    db.run(
      'UPDATE setup SET location_resource_id = ?, label = ?, shot_ids_json = ?, resource_ids_json = ?, durations_json = ?, estimate_confirmed = ?, revision = revision + 1 WHERE id = ?',
      ...values(x),
      x.id,
    );
  } else {
    db.run(
      'INSERT INTO setup (id, location_resource_id, label, shot_ids_json, resource_ids_json, durations_json, estimate_confirmed) VALUES (?, ?, ?, ?, ?, ?, ?)',
      x.id,
      ...values(x),
    );
  }
  syncShots(db, x);
}

function syncShots(db: DbPort, x: Setup): void {
  const mine = new Set(x.shot_ids);
  // shots that used to point here but are no longer listed
  for (const r of db.all<{ id: string }>('SELECT id FROM shot WHERE setup_id = ?', x.id)) {
    if (!mine.has(r.id)) db.run('UPDATE shot SET setup_id = NULL WHERE id = ?', r.id);
  }
  for (const shotId of x.shot_ids) {
    const row = db.get<{ setup_id: string | null }>('SELECT setup_id FROM shot WHERE id = ?', shotId);
    if (!row) continue;
    if (row.setup_id && row.setup_id !== x.id) {
      const other = getSetup(db, row.setup_id);
      if (other) {
        db.run(
          'UPDATE setup SET shot_ids_json = ?, revision = revision + 1 WHERE id = ?',
          JSON.stringify(other.shot_ids.filter((id) => id !== shotId)),
          other.id,
        );
      }
    }
    if (row.setup_id !== x.id) db.run('UPDATE shot SET setup_id = ? WHERE id = ?', x.id, shotId);
  }
}

/** Delete a setup; shot.setup_id is cleared and its constraints cascade (FKs). */
export function deleteSetupRow(db: DbPort, id: string): void {
  db.run('UPDATE shot SET setup_id = NULL WHERE setup_id = ?', id);
  db.run('DELETE FROM setup WHERE id = ?', id);
  const auto = readAutoSetups(db);
  if (auto[id]) {
    delete auto[id];
    writeAutoSetups(db, auto);
  }
}

/** Setups that reference a resource as location or extra resource. */
export function setupsUsingResource(db: DbPort, resourceId: string): Setup[] {
  return listSetups(db).filter((s) => s.location_resource_id === resourceId || s.resource_ids.includes(resourceId));
}

// ------------------------------------------------------------ auto markers ---

export const AUTO_KEY = 'plan.auto_setups';

/** setup id → { key: derive group key, edited: user changed it since derive } */
export type AutoSetups = Record<string, { key: string; edited: boolean }>;

export function readAutoSetups(db: DbPort): AutoSetups {
  const r = db.get<{ value_json: string }>('SELECT value_json FROM kv WHERE key = ?', AUTO_KEY);
  if (!r) return {};
  try {
    const v = JSON.parse(r.value_json) as unknown;
    if (typeof v !== 'object' || v === null || Array.isArray(v)) return {};
    const out: AutoSetups = {};
    for (const [id, m] of Object.entries(v as Record<string, unknown>)) {
      if (typeof m === 'object' && m !== null && typeof (m as { key?: unknown }).key === 'string') {
        out[id] = { key: (m as { key: string }).key, edited: (m as { edited?: unknown }).edited === true };
      }
    }
    return out;
  } catch {
    return {};
  }
}

export function writeAutoSetups(db: DbPort, auto: AutoSetups, now = new Date().toISOString()): void {
  db.run(
    'INSERT INTO kv (key, value_json, updated_at) VALUES (?, ?, ?) ON CONFLICT(key) DO UPDATE SET value_json = excluded.value_json, updated_at = excluded.updated_at',
    AUTO_KEY,
    JSON.stringify(auto),
    now,
  );
}

/** A user edit turns a derived setup into a kept one (derive keep_edited leaves it alone). */
export function markSetupEdited(db: DbPort, id: string): void {
  const auto = readAutoSetups(db);
  if (auto[id] && !auto[id].edited) {
    auto[id] = { ...auto[id], edited: true };
    writeAutoSetups(db, auto);
  }
}
